version: "3"

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data/

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./.data/redis:/data
