# Generated by Django 4.1 on 2022-08-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('petition_url', models.URLField(verbose_name='petition url')),
                ('text', models.TextField(verbose_name='text')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='publish date')),
            ],
            options={
                'db_table': 'petition',
            },
        ),
    ]
