# Generated by Django 4.1 on 2022-09-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(null=True, upload_to='users/', verbose_name='user photo'),
        ),
    ]
