# Generated by Django 4.1 on 2022-08-18 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('status', models.IntegerField(choices=[(10, 'Setup'), (20, 'Pause'), (30, 'In progress'), (40, 'Completed')], verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'db_table': 'assistance',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
            options={
                'verbose_name': 'categories',
                'verbose_name_plural': 'category',
                'db_table': 'categories',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='AssistancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('payment_url', models.URLField(max_length=240, verbose_name='payment url')),
                ('assistance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_payment', to='assistance.assistance', verbose_name='assistance')),
            ],
            options={
                'db_table': 'assistance_payment',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='AssistanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assistance/', verbose_name='image')),
                ('assistance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_images', to='assistance.assistance', verbose_name='assistance')),
            ],
            options={
                'db_table': 'assistance_images',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='AssistanceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assistance.assistancecomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'db_table': 'assistance_comments',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='assistance',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='assistance.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='assistance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assistance', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
