# Generated by Django 4.1 on 2022-09-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='status',
            field=models.CharField(choices=[('ASSISTANCE_SETUP', 'Setup'), ('ASSISTANCE_PAUSE', 'PAUSE'), ('ASSISTANCE_IPS', 'In progress'), ('ASSISTANCE_CPD', 'Completed')], max_length=150, verbose_name='status'),
        ),
        migrations.DeleteModel(
            name='AssistancePayment',
        ),
    ]
