# Generated by Django 4.1.2 on 2022-10-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='status',
            field=models.CharField(choices=[('ASSISTANCE_SETUP', 'Setup'), ('ASSISTANCE_PAUSE', 'Pause'), ('ASSISTANCE_IPS', 'In progress'), ('ASSISTANCE_CPD', 'Completed')], default='In progress', max_length=150, verbose_name='status'),
        ),
    ]
