# Generated by Django 4.1.2 on 2022-10-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0002_alter_assistance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='assistance/', verbose_name='image'),
        ),
    ]
