# Generated by Django 4.0.5 on 2022-07-03 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Name')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Aid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Image')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('payment_url', models.CharField(max_length=200, verbose_name='Payment URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_category', to='assistances.category', verbose_name='Category')),
            ],
            options={
                'db_table': 'aids',
            },
        ),
    ]
