# Generated by Django 4.0.5 on 2022-07-03 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aids', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
